### ISSUE TITLE
Mixed up file icons on GitLab

### ISSUE THREAD

**Issue by auscompgeek** [xxhomey19/github-file-icon#39]
Example: https://gitlab.com/Redrield/robot-rs

![screenshot](https://user-images.githubusercontent.com/128854/44264829-684ce080-a267-11e8-8741-2f33bdbfde23.png)

**Comment by xxhomey19** [comment]
Hi @auscompgeek thanks for report the issue.
This repo is weird. I checked other repos on GitLab, and they works just fine. The icons one this page seems to have wrong order, each icon should be placed its two below position. I'll check it out latter.

**Comment by auscompgeek** [comment]
This repo is definitely not "weird"; I found a few others with the same problem:

- https://gitlab.com/pablo.rocka/vim_config
- https://gitlab.com/absassi/asap

**Comment by xxhomey19** [comment]
That's great. I'll find out why doesn't this extension work fine in these repos. Thank you!

**Comment by xxhomey19** [comment]
@auscompgeek I have fixed it.

<img width="278" alt="screen shot 2018-08-20 at 12 51 55" src="https://user-images.githubusercontent.com/12113222/44318266-6017bf80-a478-11e8-81ae-043d4208bd49.png">

**Comment by mashehu** [comment]
Hi, 
The off-by-one shift of the icons appeared again at a private gitlab repo I have. So, maybe this bug isn't completely fixed yet or reappeared.
![Screenshot 2019-09-26 14 31 16](https://user-images.githubusercontent.com/6169021/65687864-5c3a7180-e06a-11e9-9f09-edd3f215b5e3.png)
